name: PDDL Syntax Highlighter
markdown: redcarpet
pygments: true

baseurl: "http://pold87.github.io/sublime-pddl"

navigation:
 # - text: Blog
 #   title: Newest developments
 #   url: /blog.html
 - text: Download
   title: Download lastest Version of PDDL Syntax Highlighter
   url: /download.html
 - text: Doc
   title: Read the Manual
   url: /doc.html
 - text: Online Editor
   title: Open a PDDL Online Editor
   url: /editor-info.html
 - text: About
   title: About Me
   url: /about.html
